# -*- coding: utf-8 -*-
"""
This family file was auto-generated by $Id: 50770c116c72fe8479cf5f1a79711d7cecc6cecc $
Configuration parameters:
  url = http://wiki.darkrp.com/index.php/Main_Page
  name = darkrp

Please do not commit this to the Git repository!
"""

from pywikibot import family
from pywikibot.tools import deprecated

class Family(family.Family):
    def __init__(self):
        family.Family.__init__(self)
        self.name = 'darkrp'
        self.langs = {
            'en': 'wiki.darkrp.com',
        }



    def scriptpath(self, code):
        return {
            'en': '',
        }[code]

    @deprecated('APISite.version()')
    def version(self, code):
        return {
            'en': u'1.23.5',
        }[code]
