#!/usr/bin/python
# -*- coding: utf-8  -*-

"""
Script to upload documentation generated by DarkRP to the wiki.
This script is combined with a Lua script that generates wiki pages.

Parameters:
    (first parameter) - The folder that contains the wiki tree generated by darkrp_generatewiki.
"""
import json
import pywikibot
import os.path
import os


def upload(site, path):
    with open(os.path.join(path, "index.txt"), 'r') as json_file:
        index = json.load(json_file)
        for pageName, fileName in index.items():
            f = os.path.join(path, fileName)
            page = pywikibot.Page(site, pageName)

            with open(f, 'r') as file:
                page.text = file.read()

            page.save("Wikibot updated DarkRP documentation")


def main(*args):
    path = ""
    for arg in pywikibot.handle_args(args):
        path = arg

    if not os.path.isdir(path):
        print("Invalid path: \"%s\"!" % path)
        return

    site = pywikibot.Site()
    site.login(True)

    upload(site, path)


if __name__ == "__main__":
    main()
