#!/usr/bin/python
# -*- coding: utf-8  -*-

"""
Script to upload documentation generated by DarkRP to the wiki.
This script is combined with a Lua script that generates wiki pages.

Parameters:
    (first parameter) - The folder that contains the wiki tree generated by darkrp_generatewiki.
"""
import pywikibot
import os.path

def upload(site, path):
    for root, _, files in os.walk(path):
        for name in files:
            f = os.path.join(root, name)
            pagename, _ = os.path.splitext(os.path.relpath(f, path))
            pagename = pagename.replace('\\', '/')
            print(pagename)
            page = pywikibot.Page(site, pagename)

            # Uncomment this code to enable page deletion
            # if page.exists():
            #    page.delete("Backwards slash error", False)

            with open(f, 'r') as file:
                page.text = file.read()

            page.save("Wikibot updated DarkRP documentation")


def main(*args):
    path = ""
    for arg in pywikibot.handle_args(args):
        path = arg

    if not os.path.isdir(path):
        print("Invalid path: \"%s\"!" % path)
        return

    site = pywikibot.Site()
    site.login(True)

    upload(site, path)


if __name__ == "__main__":
    main()
